apiVersion: skaffold/v1beta16
kind: Config
metadata:
  name: nodejs-docker-webapp
build:
  artifacts:
  - image: eu.gcr.io/kubehube/azmattil-nodejs-docker-webapp
deploy:
  kubectl:
    manifests:
    - k8s-pod.yaml
